### ISSUE TITLE
 <type 'exceptions.NameError'> when using option "earth date"

### ISSUE THREAD

**Issue by jmoeckel** [aymeric-spiga/mcd_python#17]
In the web interface, enabling the radio button for `earth date` results in an `<type 'exceptions.NameError'> ` (see screenshot for the complete exception).

![unbenannt](https://user-images.githubusercontent.com/8668368/33425767-011ca306-d5c0-11e7-96e4-4fdb24af4c7b.JPG)

I assume, that the error is in the if-condition starting in line 119 in the corresponding file: The else condition does not set `islsfree`.

**Comment by aymeric-spiga** [comment]
Many thanks @jmoeckel you guessed right, I am about to correct the problem
